In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [5]:
a = np.arange(1,10,3)
print(a)

[1 4 7]


In [8]:
a = np.linspace(1,12,4)

In [9]:
print(a)

[ 1.          4.66666667  8.33333333 12.        ]


In [10]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [12]:
a = np.full((6,),88)
print(a)

[88 88 88 88 88 88]


In [13]:
a = np.fromstring('25 30 35 40',dtype=int,sep=' ')

In [14]:
print(a)

[25 30 35 40]


In [15]:
a = np.zeros_like(a)
print(a)

[0 0 0 0]


In [19]:
a = np.empty(5,dtype=int)
print(a)

[1 2 3 4 5]


In [20]:
a = np.sort([9,5,1,6,8])
print(a)

[1 5 6 8 9]
